name: 'Hello There'
description: 'Fun with GH actions'
inputs:
  who-to-greet:
    description: 'Person to greet'
    required: true
    default: 'General Grevious'
outputs:
  time:
    description: 'Time of greeting'
runs:
  using: 'node16'
  main: 'index.js'